# Generated by Django 5.0.4 on 2024-04-09 11:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Post Title')),
                ('category', models.CharField(choices=[('0', 'featured'), ('1', 'normal')], max_length=50)),
                ('fram', models.CharField(choices=[('0', 'django'), ('1', 'flask'), ('3', 'featured')], max_length=50)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Compose Content')),
                ('summary', models.TextField(verbose_name='Post Summary')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
