# Generated by Django 5.0.4 on 2024-04-09 11:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fram',
        ),
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('featured', 'Избранные'), ('politics', 'Политика'), ('business_economy', 'Бизнес и экономика'), ('culture', 'Культура'), ('technology', 'Технологии'), ('sports', 'Спорт'), ('education', 'Образование'), ('environment', 'Окружающая среда'), ('travel_tourism', 'Путешествия и туризм'), ('local_news', 'Местные новости'), ('international_news', 'Мировые новости')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок поста'),
        ),
    ]
