# Generated by Django 5.0.4 on 2024-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_name_alter_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('featured', 'Избранные'), ('politics', 'Политика'), ('business_economy', 'Бизнес и экономика'), ('culture', 'Культура'), ('technology', 'Технологии'), ('sports', 'Спорт'), ('education', 'Образование'), ('environment', 'Окружающая среда'), ('travel_tourism', 'Путешествия и туризм'), ('local_news', 'Местные новости'), ('international_news', 'Мировые новости')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='core.category', verbose_name='Категории'),
        ),
    ]
